# AeroSpace Configuration
# Enhanced config matching yabai/skhd workflow
# See: https://github.com/nikitabobko/AeroSpace

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Matches yabai's mouse_follows_focus = on
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (matches yabai config: 4px all around, 0.9 bottom)
[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       4
outer.bottom =     1  # Matches yabai's 0.9 (rounded up)
outer.top =        4
outer.right =      4

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# ============================================================================
# Applications (matches skhd: cmd-return for kitty)
# ============================================================================
cmd-enter = 'exec-and-forget open -na /Applications/Kitty.app'

# ============================================================================
# Window Navigation (matches skhd: alt-hjkl)
# ============================================================================
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# ============================================================================
# Moving Windows (matches skhd: shift+alt-hjkl)
# ============================================================================
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# ============================================================================
# Monitor/Display Focus (matches skhd: alt-s/g for west/east)
# ============================================================================
alt-s = 'focus-monitor left'
alt-g = 'focus-monitor right'

# Move window to monitor (matches skhd: shift+alt-s/g)
alt-shift-s = 'move-node-to-monitor left'
alt-shift-g = 'move-node-to-monitor right'

# ============================================================================
# Window Resizing (matches skhd behavior)
# ============================================================================
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# ============================================================================
# Layout Modifications (matches skhd: shift+alt-r/y/x)
# ============================================================================
alt-shift-r = 'layout tiles horizontal vertical'  # Rotate/toggle layout
alt-shift-y = 'layout tiles vertical horizontal'  # Mirror Y-axis equivalent
alt-shift-x = 'layout tiles horizontal vertical'  # Mirror X-axis equivalent

# ============================================================================
# Window State Toggles (matches skhd)
# ============================================================================
alt-shift-t = 'layout floating tiling'   # Toggle floating (shift+alt-t)
alt-shift-m = 'fullscreen'               # Maximize/fullscreen (shift+alt-m)
alt-shift-e = 'balance-sizes'            # Balance windows (shift+alt-e)

# ============================================================================
# Workspace Switching (Only 1-6 to avoid empty workspaces)
# Labels: Start/Comms/Browser/Code/Org/Games
# ============================================================================
alt-1 = 'workspace 1'  # Start
alt-2 = 'workspace 2'  # Comms
alt-3 = 'workspace 3'  # Browser
alt-4 = 'workspace 4'  # Code
alt-5 = 'workspace 5'  # Org
alt-6 = 'workspace 6'  # Games

# ============================================================================
# Move Window to Workspace (Only 1-6)
# ============================================================================
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'

# ============================================================================
# Workspace Navigation (matches skhd: shift+alt-p/n for prev/next)
# ============================================================================
alt-shift-p = 'workspace --wrap-around prev'
alt-shift-n = 'workspace --wrap-around next'

# Workspace cycling with Alt+Tab (like switching desktops)
alt-tab = 'workspace --wrap-around next'
alt-shift-tab = 'workspace --wrap-around prev'

# Workspace back-and-forth (jump to previous workspace)
alt-backtick = 'workspace-back-and-forth'

# Move workspace to different monitor (using alt-shift-w for "workspace")
alt-shift-w = 'move-workspace-to-monitor --wrap-around next'

# ============================================================================
# Window Cycling
# Note: macOS Alt+` natively cycles between windows of the same app
# This is perfect for multiple code workspaces or terminal windows.
# ============================================================================

# ============================================================================
# Utility Commands
# ============================================================================
# Organize windows into their designated workspaces
# Organize windows into workspaces
alt-shift-o = 'exec-and-forget aerospace-organize'

# ============================================================================
# Service Mode (advanced operations)
# ============================================================================
alt-shift-semicolon = 'mode service'

# ============================================================================
# Service Mode - Advanced Operations (alt+shift+;)
# ============================================================================
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']  # Reset layout
f = ['layout floating tiling', 'mode main']  # Toggle floating
backspace = ['close-all-windows-but-current', 'mode main']

# Join windows (like i3 tabbed/stacked)
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# Note: sticky windows not yet supported in AeroSpace
# See: https://github.com/nikitabobko/AeroSpace/issues/2

# ============================================================================
# Workspace Auto-Assignment (matches yabai rules)
# Get app-id by running: aerospace list-apps
#
# IMPORTANT: These rules only apply to NEWLY OPENED windows!
# To apply to existing windows:
# 1. Reload config: Alt+Shift+; then Esc
# 2. Manually move windows: Alt+Shift+[1-6]
# 3. Or restart AeroSpace
# ============================================================================

# ----------------------------------------------------------------------------
# Workspace 1: Start
# ----------------------------------------------------------------------------
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'move-node-to-workspace 1'

# Add Filezilla and Todoist if you use them
# [[on-window-detected]]
# if.app-id = 'org.filezilla-project.filezilla'
# run = 'move-node-to-workspace 1'

# ----------------------------------------------------------------------------
# Workspace 2: Comms (Personal Communications)
# ----------------------------------------------------------------------------
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace 2'

# ----------------------------------------------------------------------------
# Workspace 3: Browser
# ----------------------------------------------------------------------------
[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 3'

# ----------------------------------------------------------------------------
# Workspace 4: Code (Programming)
# ----------------------------------------------------------------------------
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = 'move-node-to-workspace 4'

# ----------------------------------------------------------------------------
# Workspace 5: Org (Organization - Calendar, Mail)
# ----------------------------------------------------------------------------
[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace 5'

# ----------------------------------------------------------------------------
# Workspace 6: Games (Note: These should be floating in yabai)
# AeroSpace doesn't have per-workspace layout settings yet
# These apps will default to floating via the layout.floating rules below
# ----------------------------------------------------------------------------
[[on-window-detected]]
if.app-id = 'com.riotgames.LeagueofLegends.GameClient'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.riotgames.RiotClient'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 6'

# ============================================================================
# Apps to Always Float (matches yabai manage=off rules)
# ============================================================================
[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.SystemPreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.archiveutility'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Dictionary'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.videolan.vlc'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.virtualbox.app.VirtualBox'
run = 'layout floating'

# Game launchers and clients should be floating
[[on-window-detected]]
if.app-id = 'com.riotgames.LeagueofLegends.GameClient'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.riotgames.RiotClient'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.valvesoftware.steam'
run = 'layout floating'
