#!/bin/sh
# If emacs does not have an instance, start one and open.
HOMEBREWEMACS="/opt/homebrew/bin/emacs"
EMACS="/usr/bin/emacs"

if [ ! -f "$HOMEBREWEMACS" ]; then
	EMACS="/opt/homebrew/bin/emacs"
	EMACSCLIENT="/opt/homebrew/bin/emacsclient"
elif [ ! -f "$EMACS" ]; then
	EMACS="/usr/bin/emacs"
	EMACSCLIENT="/usr/bin/emacsclient"
fi

$EMACSCLIENT -n -a emacs $@ &
#$EMACSCLIENT -c '' $@
#i3-msg "[class=Emacs] focus"
