export EDITOR="$HOME/.bin/em"
export TERMINAL="urxvt"
export READER="zathura"
export FILE="ranger"
export ALTERNATE_EDITOR=""
export BROWSER="brave-browser"
export EMAIL="me@kfring.com"
export GOPATH="/usr/bin"
export GPG_TTY=$(tty)
export HISTFILESIZE=20000
export HOMEBREW_NO_ANALYTICS=1
export LANG="en_US"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export NAME="Kyle E. Fring"
export PROMPT_DIRTRIM=3
